Contrakt/Contrakt/urls.py
from django.contrib import admin
from django.urls import path, include
from autenticacao.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contratos/', include('contratos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

Contrakt/urls.py
from django.contrib import admin
from django.urls import path, include
from autenticacao.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contratos/', include('contratos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

autenticacao/urls.py
from django.urls import path
from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register_view, name='register'),
    path('forgot/', views.forgot_view, name='forgot'),
    path('login-submit/', views.login_submit, name='login_submit'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from autenticacao.views import index, login_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contratos/', include('contratos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
]

Contrakt/autenticacao/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import password_validation
from django.db import models

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)  # Adiciona o campo de email

    class Meta:
        db_table = 'autenticacao_customuser'

    def save(self, *args, **kwargs):
        # Executar as validações de senha antes de salvar o usuário
        password_validation.validate_password(self.password)
        super().save(*args, **kwargs)

autenticacao/models.py
from django.contrib.auth.models import AbstractUser # classe
from django.contrib.auth import password_validation # modulo
from django.db import models

# Estendendo a classe abstractuser
class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)  # Adiciona o campo de email(deixa o campo unico)

    class Meta:
        db_table = 'autenticacao_customuser'

    def save(self, *args, **kwargs):
        # Executar as validações de senha antes de salvar o usuário
        password_validation.validate_password(self.password)
        super().save(*args, **kwargs)

Contrakt/autenticacao/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2')

    def clean_email(self):                              # validar se o email já está em uso
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Este email já está em uso.')
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

autenticacao/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm

#estendendo UserCreationForm
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True) # campo obrigatorio

    class Meta:
        model = CustomUser #  formulário será baseado no modelo CustomUser
        fields = ('email', 'password1', 'password2')

    def clean_email(self):                              # validar se o email já está em uso, Personalização da validação
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('This email is already in use.')
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

Contrakt/autenticacao/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib import messages

def index(request) :
    if request.user.is_authenticated:  # Verifica se o usuário já está autenticado
        return redirect('contratos:contract_list')
    return render(request, 'autenticacao/index.html')


def forgot_view(request) :
    if request.user.is_authenticated:  # Verifica se o usuário já está autenticado
        return redirect('contratos:contract_list')
    return render(request, 'autenticacao/forgot.html')


def register_view(request) :
    if request.user.is_authenticated:  # Verifica se o usuário já está autenticado
        return redirect('contratos:contract_list')
    if request.method == 'POST' :
        form = RegistrationForm(request.POST)
        if form.is_valid() :
            try :
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password1')
                user = form.save(commit=False)
                user.username = email  # Define o email como username
                user.set_password(password)  # Define a senha
                user.save()
                messages.success(request, 'Registration successful. You can now log in.')
                login(request, user)  # Realizar login automático após o registro
                return redirect('autenticacao:index')
            except Exception as e :
                messages.error(request, f'Registration failed: {str(e)}')
        else :
            messages.error(request, 'Invalid form submission. Please check the form data.')
    else :
        form = RegistrationForm()
    return render(request, 'autenticacao/register.html', {'form' : form})


def login_submit(request) :
    if request.method == 'POST' :
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)
        if user is not None :
            login(request, user)
            return redirect('contratos:contract_list')
        else :
            messages.error(request, 'Invalid email or password. Please try again.')

    return redirect('autenticacao:index')

autenticacao/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.contrib.auth import authenticate, login, update_session_auth_hash        # nao estou usando update_session
from django.contrib import messages


def index(request) :
    if request.user.is_authenticated:  # Verifica se o usuário já está autenticado
        return redirect('contratos:contract_list')
    return render(request, 'autenticacao/index.html')


def forgot_view(request) :
    if request.user.is_authenticated:  # Verifica se o usuário já está autenticado
        return redirect('contratos:contract_list')
    return render(request, 'autenticacao/forgot.html')


def register_view(request) :
    if request.user.is_authenticated:  # Verifica se o usuário já está autenticado
        return redirect('contratos:contract_list')
    if request.method == 'POST' :
        form = RegistrationForm(request.POST)
        if form.is_valid() :
            try :
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password1')
                user = form.save(commit=False)
                user.username = email  # Define o email como username
                user.set_password(password)  # Define a senha
                user.save()
                messages.success(request, 'Registration successful. You can now log in.')
                login(request, user)  # Realizar login automático após o registro
                return redirect('autenticacao:index')
            except Exception as e :
                messages.error(request, f'Registration failed: {str(e)}')
        else :
            messages.error(request, 'Invalid form submission. Please check the form data.')
    else :
        form = RegistrationForm()
    return render(request, 'autenticacao/register.html', {'form' : form})


def login_submit(request) :
    if request.method == 'POST' :
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)
        if user is not None :
            login(request, user)
            return redirect('contratos:contract_list')
        else :
            messages.error(request, 'Invalid email or password. Please try again.')

    return redirect('autenticacao:index')

Contrakt/autenticacao/templates/autenticacao/forgot.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Forgot Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
<section class="h-100">
    <div class="container h-100">
        <div class="row justify-content-sm-center h-100">
            <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
                <div class="text-center my-5">
                    <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="logo" width="100">
                </div>
                <div class="card shadow-lg">
                    <div class="card-body p-5">
                        <h1 class="fs-4 card-title fw-bold mb-4">Forgot Password</h1>
                        <form method="POST" class="needs-validation" novalidate="" autocomplete="off">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label class="mb-2 text-muted" for="email">E-Mail Address</label>
                                <input id="email" type="email" class="form-control" name="email" value="" required
                                       autofocus>
                                <div class="invalid-feedback">
                                    Email is invalid
                                </div>
                            </div>

                            <div class="d-flex align-items-center">
                                <button type="submit" class="btn btn-primary ms-auto">
                                    Send Link
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer py-3 border-0">
                        <div class="text-center">
                            Remember your password? <a href="{% url 'autenticacao:index' %}" class="text-dark">Login</a>
                        </div>
                    </div>
                </div>
                <div class="text-center mt-5 text-muted">
                    Copyright &copy; 2023-2023 &mdash; Contrakt
                </div>
            </div>
        </div>
    </div>
</section>
</body>

</html>

Contrakt/autenticacao/templates/autenticacao/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Contrakt Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
<section class="h-100">
    <div class="container h-100">
        <div class="row justify-content-sm-center h-100">
            <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
                <div class="text-center my-5">
                    <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="logo" width="100">
                </div>
                <div class="card shadow-lg">
                    <div class="card-body p-5">
                        <h1 class="fs-4 card-title fw-bold mb-4">Login</h1>
                        <form method="POST" action="{% url 'autenticacao:login_submit' %}" class="needs-validation"
                              novalidate="" autocomplete="off">
                            {% csrf_token %}
                            {% if messages %}
                            {% for message in messages %}
                            <div class="alert alert-danger" role="alert">{{ message }}</div>
                            {% endfor %}
                            {% endif %}
                            <div class="mb-3">
                                <label class="mb-2 text-muted" for="email">E-Mail Address</label>
                                <input id="email" type="email" class="form-control" name="email" value="" required
                                       autofocus>
                                <div class="invalid-feedback">
                                    Email is invalid
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="mb-2 w-100">
                                    <label class="text-muted" for="password">Password</label>
                                    <a href="{% url 'autenticacao:forgot' %}" class="float-end">
                                        Forgot Password?
                                    </a>
                                </div>
                                <input id="password" type="password" class="form-control" name="password" required>
                                <div class="invalid-feedback">
                                    Password is required
                                </div>
                            </div>

                            <div class="d-flex align-items-center">
                                <button id="login-button" type="submit" class="btn btn-primary ms-auto">
                                    Login
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer py-3 border-0">
                        <div class="text-center">
                            Don't have an account? <a href="{% url 'autenticacao:register' %}" class="text-dark">Create
                            One</a>
                        </div>
                    </div>
                </div>
                <div class="text-center mt-5 text-muted">
                    <div class="text-center mt-5 text-muted">
                        &copy; Contrakt
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>

</html>

Contrakt/autenticacao/templates/autenticacao/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>

<body>
<section class="h-100">
    <div class="container h-100">
        <div class="row justify-content-sm-center h-100">
            <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
                <div class="text-center my-5">
                    <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="logo" width="100">
                </div>
                <div class="card shadow-lg">
                    <div class="card-body p-5">
                        <h1 class="fs-4 card-title fw-bold mb-4">Register</h1>
                        <form method="POST" class="needs-validation" novalidate="" autocomplete="off">
                            {% csrf_token %}

                            <div class="mb-3">
                                <label for="id_email" class="form-label">Email</label>
                                <input type="email" name="email" id="id_email"
                                       class="form-control {% if form.errors.email %}is-invalid{% endif %}"
                                       placeholder="Email" required>
                                {% if form.errors.email %}
                                <div class="invalid-feedback">
                                    {{ form.errors.email }}
                                </div>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                <label for="id_password1" class="form-label">Password</label>
                                <input type="password" name="password1" id="id_password1"
                                       class="form-control {% if form.errors.password1 %}is-invalid{% endif %}"
                                       placeholder="Password" required>
                                {% if form.errors.password1 %}
                                <div class="invalid-feedback">
                                    {{ form.errors.password1 }}
                                </div>
                                {% endif %}
                            </div>

                            <div class="mb-3">
                                <label for="id_password2" class="form-label">Confirm Password</label>
                                <input type="password" name="password2" id="id_password2"
                                       class="form-control {% if form.errors.password2 %}is-invalid{% endif %}"
                                       placeholder="Confirm Password" required>
                                {% if form.errors.password2 %}
                                <div class="invalid-feedback">
                                    {{ form.errors.password2 }}
                                </div>
                                {% endif %}
                            </div>

                            <p class="form-text text-muted mb-3">
                                By registering you agree with our terms and condition.
                            </p>

                            <div class="align-items-center d-flex">
                                <button type="submit" class="btn btn-primary ms-auto">
                                    Register
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer py-3 border-0">
                        <div class="text-center">
                            Already have an account? <a href="{% url 'autenticacao:index' %}"
                                                        class="text-dark">Login</a>
                        </div>
                    </div>
                </div>
                <div class="text-center mt-5 text-muted">
                    Copyright &copy; 2023-2023 &mdash; Contrakt
                </div>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/login.js' %}"></script>
</body>

</html>